# file: group_vars/all/diaspora.yaml
#
# ansible-vault encrypt this file
#
---
#diaspora_db_name: 'diaspora_db'
#diaspora_db_username: 'diaspora_user'
#diaspora_db_password: 'dAuDUMMYxDEXAMPLEO+iqPlc'
